travis:
  secure:
    BINSTAR_TOKEN: Y08cVOmojvDnYZJlACY25vKFIO+hAqb4DviJNgdUav3VIep+smUUoD+hOHxK0X04nVQW/q1G6dO8U95GEN9q+HZ/41ZDoeX9w+3IBdSAXF81FV8+9BWQGwpVl0m+PSjUPq9NRrvFjey1gUkizSSmwqKOjIBhguEce266YAZN8ahNeVkDUQkoiXzV50njcxUNKB3VvoUYXSXux9lmqoGGVXYEU7dxIGK0/K3dtPXQqEfi6m/TPtycxHIrH+e8EPlr1ctGviCauMKlFO1QmbiRD0ubnHonMjnUYSvQQeM83ieejIVx1aMi5iWaCOFAO227K+waeb8LVcnKUNBZpJgCri92UfYG9wIjhzuyNADroNcd943mT7yrP8wgN/KtmjYP7qo9TQoVQhnkr1ThMeQSPinlqZ/Bw6omA6/J+0M7kwhy/ftrN77fO1a/rnRSVqm1x+101vkbATTOG1H0gUJ9CkdW2sG5/0zs6dICvKOTmzORppe9YIuPviHqB9qqFxVjQBcj2KaSOhXU/IM9CG/N1MvqOK6YFcAIgUJGo56lSW6bdQQA9q+cYf2WcbEcgAewITVEGHplHCDdKc7dtmqEl7Ug73gZSbr3OoCUzJTwFgsA2vhHPgK4Xfu9t4RdVIYWCj7yXUeeq4KFgS6h+PvEFy3VL27u5NOo7NMQsmbYVXQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
